name: Build & Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.405
    - name: Install dependencies
      run: dotnet restore
    - name: Clean
      run: dotnet clean MediaWikiApiTest.sln --configuration Release && dotnet nuget locals all --clear
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: MediaWikiApiTest
      run: dotnet test